USE Vc;
INSERT INTO publicaciones_tipo (nombre) VALUES 
('Ropa Superior'),
('Ropa Inferior'),
('Ropa Interior'),
('Ropa de Abrigo'),
('Ropa Deportiva'),
('Ropa Formal / de Oficina'),
('Ropa de Noche / Fiesta'),
('Accesorios'),
('Ropa de Baño'),
('Ropa Casual'),
('Ropa de Maternidad'),
('Ropa de Trabajo / Uniformes');

INSERT INTO estado_publicacion (estado) VALUES 
('Activa'),
('Pendiente'),
('Vendido');

INSERT INTO estado_ropa (estado) VALUES 
('Nuevo'),
('Como Nuevo'),
('Buen Estado'),
('Usado'),
('Mal Estado'),
('Muy Mal Estado');


INSERT INTO `prendas` (`prenda`) VALUES
('Camisetas / Remeras'),
('Camisas'),
('Blusas'),
('Suéteres / Jerseys'),
('Chalecos'),
('Abrigos'),
('Pantalones'),
('Shorts'),
('Faldas'),
('Leggings'),
('Calzoncillos / Bóxers'),
('Sujetadores'),
('Tangas / Calzones'),
('Chaquetas'),
('Abrigos'),
('Parkas'),
('Bermudas'),
('Pantalones deportivos'),
('Chándales'),
('Leggings deportivos'),
('Camisetas deportivas'),
('Trajes'),
('Camisas de vestir'),
('Pantalones de vestir'),
('Blazers'),
('Vestidos'),
('Tops de fiesta'),
('Faldas de noche'),
('Pantalones de noche'),
('Bufandas'),
('Gorros / Sombreros'),
('Guantes'),
('Cinturones'),
('Relojes'),
('Lentes de sol'),
('Bikinis'),
('Bañadores'),
('Shorts de baño'),
('Jeans'),
('Joggers'),
('Camisetas de manga larga o corta'),
('Sudaderas'),
('Vestidos de maternidad'),
('Pantalones de maternidad'),
('Overoles'),
('Batas'),
('Uniformes escolares');

INSERT INTO `ropa_categorias` (`category`) VALUES
('Todos'),
('Ropa Superior'),
('Ropa Inferior'),
('Ropa Interior'),
('Ropa de Abrigo'),
('Ropa Deportiva'),
('Ropa Formal / de Oficina'),
('Ropa de Noche / Fiesta'),
('Accesorios'),
('Ropa de Baño'),
('Ropa Casual'),
('Ropa de Maternidad'),
('Ropa de Trabajo / Uniformes');
